export enum ECONOMIC_BALANCE_ENUM {
  PRODUCTION = "PRODUCTION",
  CONSUMPTION = "CONSUMPTION",
  DEFICIT = "DEFICIT",
}

export type ECONOMIC_BALANCE =
  (typeof ECONOMIC_BALANCE_ENUM)[keyof typeof ECONOMIC_BALANCE_ENUM];
